stages:
  - build
  #- test
  - staging
  - deploy

variables:
  # Image name using GitLab registry
  IMAGE_NAME: "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME"
  #DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

# Build Docker image and push it to GitLab container registry
build:
  stage: build
  image: docker:latest
  before_script:
    - echo $IMAGE_NAME
    - echo "$CI_REGISTRY_PASS" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - echo "Building Docker image for Next.js app..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
  only:
    - main
    - staging

# Run tests inside the Docker container
# test:
#   stage: test
#   image: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
#   script:
#     - echo "Running tests for Next.js app inside built container on the runner machine..."
#     - docker run --rm "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME" npm run lint  # Run the lint tests inside the container
#   only:
#     - staging
#     - main

# Deploy to the staging server
stage:
  stage: staging
  script:
    - echo "Deploying to staging server..."
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_HOST_STAGING << 'EOF'
        docker pull $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
        docker stop nextjs-app || true
        docker rm nextjs-app || true
        docker run -d --name nextjs-app -p 80:80 $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
      EOF
  only:
    - staging

# Deploy to production server
deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_HOST_PROD << 'EOF'
        docker pull $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
        docker stop nextjs-app || true
        docker rm nextjs-app || true
        docker run -d --name nextjs-app -p 80:80 $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
      EOF
  only:
    - main
