stages:
  - install
  - build
  - test
  - deploy


install_dependencies:
  stage: install
  script:
    - pwd
    - npm install
  artifacts:
    paths:
      - node_modules/

build_application:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/

test_application:
  stage: test
  script:
    - npm run test

deploy_application:
  stage: deploy
  only:
    - main  # Deploy only when pushing to the main branch
  script:
    - echo "Deploying the Next.js application..."
    - npm run dev
    - echo "Deployment complete!"